// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using scoreGr03.Data;

#nullable disable

namespace scoreGr03.Migrations
{
    [DbContext(typeof(scoreGr03Context))]
    partial class scoreGr03ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("scoreGr03.Models.But", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Temps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.HasIndex("MatchId");

                    b.ToTable("But");
                });

            modelBuilder.Entity("scoreGr03.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipe");
                });

            modelBuilder.Entity("scoreGr03.Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Joueur");
                });

            modelBuilder.Entity("scoreGr03.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EquipeDomicileId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipeExterieurId")
                        .HasColumnType("int");

                    b.Property<int>("ScoreDomicile")
                        .HasColumnType("int");

                    b.Property<int>("ScoreExterieur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeDomicileId");

                    b.HasIndex("EquipeExterieurId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("scoreGr03.Models.But", b =>
                {
                    b.HasOne("scoreGr03.Models.Joueur", "Joueur")
                        .WithMany()
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("scoreGr03.Models.Match", "Match")
                        .WithMany("Buts")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("scoreGr03.Models.Joueur", b =>
                {
                    b.HasOne("scoreGr03.Models.Equipe", "Equipe")
                        .WithMany("Joueurs")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("scoreGr03.Models.Match", b =>
                {
                    b.HasOne("scoreGr03.Models.Equipe", "EquipeDomicile")
                        .WithMany()
                        .HasForeignKey("EquipeDomicileId");

                    b.HasOne("scoreGr03.Models.Equipe", "EquipeExterieur")
                        .WithMany()
                        .HasForeignKey("EquipeExterieurId");

                    b.Navigation("EquipeDomicile");

                    b.Navigation("EquipeExterieur");
                });

            modelBuilder.Entity("scoreGr03.Models.Equipe", b =>
                {
                    b.Navigation("Joueurs");
                });

            modelBuilder.Entity("scoreGr03.Models.Match", b =>
                {
                    b.Navigation("Buts");
                });
#pragma warning restore 612, 618
        }
    }
}
